chore: added unmarshal and validate capability
replicatedhq/kurlkinds pull request #3
Opened 2022-10-20 14:26 UTC by ricardomaraschini

This PR adds an auxiliar function to allow for linting directly out of `yaml` content. This new function parses the content into an Installer struct and then applies regular linting using the resulting object.

2022-10-25 17:53 UTC, emosbaugh requested changes

2022-10-25 17:53 UTC, emosbaugh commented on pkg/lint/tests/rego/openebs_gte_2.12.9_cstor.yaml
> +  - message: OpenEBS versions >= 2.12.9 dont support cStor in kurl
```suggestion
  - message: OpenEBS add-on versions >= 2.12.9 do not support cStor
```

2022-10-25 17:53 UTC, emosbaugh commented on pkg/lint/rego/output.rego
> +		"message": "OpenEBS versions >= 2.12.9 dont support cStor in kurl",
```suggestion
		"message": "OpenEBS add-on versions >= 2.12.9 do not support cStor",
```

2022-10-25 17:53 UTC, emosbaugh commented on pkg/lint/tests/rego/pod_cidr_only_mask.yaml
> +      applicationSlug: puppet-application-manager
lets remove our vendor's names from the project

2022-10-26 07:15 UTC, ricardomaraschini commented on pkg/lint/tests/rego/pod_cidr_only_mask.yaml
> +      applicationSlug: puppet-application-manager
Fixed.

2022-10-26 13:20 UTC, emosbaugh approved these changes

2022-10-26 13:59 UTC, merged