feat: preparing terrain for lint suggestions.
replicatedhq/kurlkinds pull request #63
Opened 2023-02-17 14:32 UTC by ricardomaraschini

uses json patch as a means of providing a patch that, when applied on top of the installer, can solve the lint complain.

2023-02-21 11:46 UTC, camilamacedo86 commented on pkg/lint/lint.go
> +	Patch    jsonpatch.Patch `json:"patch,omitempty"`
All can be really empty?
Could we use `omitempty` only for the fields that can actually be empty?

2023-02-21 11:46 UTC, camilamacedo86 commented on pkg/lint/lint.go
> +	data, err := json.Marshal(rs[0].Expressions[0].Value)
Are we checking if [0] is not null?
Could not it be nil?

2023-02-21 11:50 UTC, camilamacedo86 commented on pkg/lint/tests/infosev/happy_path.yaml
> +installer:
Not part of this PR, but would be great if we could create name the dir tests with testdata which has an specific meaning for golang.

2023-02-21 11:51 UTC, camilamacedo86 commented on pkg/lint/tests/infosev/upgrades_available.yaml
> +        value: 1.88.0
We have none tests with warnings.
Probably because we have no warning severity so far and we need to add the rule first.
So, that is fine.

2023-02-21 12:13 UTC, ricardomaraschini commented on pkg/lint/lint.go
> +	Patch    jsonpatch.Patch `json:"patch,omitempty"`
jsonpatch.Patch is a slice so it can be empty.

2023-02-21 12:14 UTC, ricardomaraschini commented on pkg/lint/lint.go
> +	data, err := json.Marshal(rs[0].Expressions[0].Value)
This has been like that since forever. That being said, it does not hurt to check that out and return an error if empty. Will check that out.

2023-02-21 12:18 UTC, ricardomaraschini commented on pkg/lint/lint.go
> +	data, err := json.Marshal(rs[0].Expressions[0].Value)
Ops, seems like we are already checking if they are empty, a few lines above this expression.

2023-02-21 13:04 UTC, camilamacedo86 commented on pkg/lint/lint.go
> +	Patch    jsonpatch.Patch `json:"patch,omitempty"`
Hi @ricardomaraschini,

My point here was not about  `jsonpatch.Patch ` . It was about ALL specs.
Can all be empty? Can we have lint where the Type  or the Severity is empty? I do not think so

2023-02-21 13:05 UTC, camilamacedo86 commented on pkg/lint/lint.go
> +	Type     string          `json:"type,omitempty"`
```suggestion
	Type     string          `json:"type"`
```

2023-02-21 13:05 UTC, camilamacedo86 commented on pkg/lint/lint.go
> +	Severity Severity        `json:"severity,omitempty"`
```suggestion
	Severity Severity        `json:"severity"`
```

2023-02-21 13:06 UTC, camilamacedo86 commented on pkg/lint/lint.go
> +	Field    string          `json:"field,omitempty"`
```suggestion
	Field    string          `json:"field"`
```

Could we have a lint check without define the spec/field to be checked?

2023-02-21 13:17 UTC, ricardomaraschini commented on pkg/lint/lint.go
> +	Patch    jsonpatch.Patch `json:"patch,omitempty"`
Why do you think we should show empty fields and not simply omit them ?

2023-02-21 15:09 UTC, ricardomaraschini commented on pkg/lint/lint.go
> +	Patch    jsonpatch.Patch `json:"patch,omitempty"`
Nevermind, I am OK with it. Removed all `omitempty` except for the `Patch` property.

2023-02-21 17:18 UTC, camilamacedo86 submitted a review, later dismissed

2023-02-21 17:28 UTC, emosbaugh requested changes

2023-02-21 17:28 UTC, emosbaugh commented on pkg/lint/rego/output.rego
> +			{ "op": "replace", "path": "/spec/openebs/version", "value": newest_add_on_version("openebs") }
if cstor is enabled then we should not prompt them to upgrade openebs as its not supported in later versions and instead should prompt to downgrade k8s

2023-02-21 17:28 UTC, emosbaugh commented on pkg/lint/rego/output.rego
> +			{ "op": "replace", "path": "/spec/rook/version", "value": newest_add_on_version("rook") }
should we really recommend they upgrade rook here? it will require they add a block device. perhaps its better to ask them to downgrade k8s?

2023-02-21 17:28 UTC, emosbaugh commented on pkg/lint/rego/output.rego
> +			{ "op": "replace", "path": "/spec/rook/version", "value": newest_add_on_version("rook") }
should we really recommend they upgrade rook here? it will require they add a block device. perhaps its better to ask them to downgrade k8s?

2023-02-21 17:28 UTC, emosbaugh commented on pkg/lint/rego/output.rego
> +			{ "op": "replace", "path": "/spec/rook/version", "value": newest_add_on_version("rook") }
why prompt to upgrade rook here?

2023-02-21 18:24 UTC, emosbaugh commented on pkg/lint/rego/output.rego
> +			{ "op": "replace", "path": "/spec/rook/version", "value": newest_add_on_version("rook") }
thinking more about this i dont think we should ever recommend downgrading

2023-02-21 18:24 UTC, emosbaugh commented on pkg/lint/rego/output.rego
> +			{ "op": "replace", "path": "/spec/rook/version", "value": newest_add_on_version("rook") }
thinking more about this i dont think we should ever recommend downgrading

2023-02-21 18:24 UTC, emosbaugh commented on pkg/lint/rego/output.rego
> +			{ "op": "replace", "path": "/spec/openebs/version", "value": newest_add_on_version("openebs") }
thinking more about this i dont think we should ever recommend downgrading

2023-02-21 18:25 UTC, emosbaugh commented on pkg/lint/rego/output.rego
> +			{ "op": "replace", "path": "/spec/openebs/version", "value": newest_add_on_version("openebs") }
perhaps in this case we should not recommend a patch

2023-02-21 18:26 UTC, emosbaugh commented on pkg/lint/rego/output.rego
> +			{ "op": "replace", "path": "/spec/rook/version", "value": newest_add_on_version("rook") }
i am undecided here on whether it is better to omit the patch or to recommend openebs

2023-02-21 18:26 UTC, emosbaugh commented on pkg/lint/rego/output.rego
> +			{ "op": "replace", "path": "/spec/rook/version", "value": newest_add_on_version("rook") }
i am undecided here on whether it is better to omit the patch or to recommend openebs

2023-02-22 09:17 UTC, ricardomaraschini commented on pkg/lint/lint.go
> +	Message  string          `json:"message"`
No, it can't.

2023-02-22 09:41 UTC, ricardomaraschini commented on pkg/lint/rego/output.rego
> +			{ "op": "remove", "path": "/spec/kubernetes/serviceCIDR" }
I have removed the `patch` in all CIDR cases.

2023-02-22 09:41 UTC, ricardomaraschini commented on pkg/lint/rego/output.rego
> +			{ "op": "remove", "path": "/spec/kubernetes/serviceCidrRange" }
done.

2023-02-22 09:42 UTC, ricardomaraschini commented on pkg/lint/rego/output.rego
> +			{ "op": "remove", "path": "/spec/weave/podCidrRange" }
done.

2023-02-22 09:42 UTC, ricardomaraschini commented on pkg/lint/rego/output.rego
> +			{ "op": "remove", "path": "/spec/weave/podCIDR" }
done.

2023-02-22 09:42 UTC, ricardomaraschini commented on pkg/lint/rego/output.rego
> +			{ "op": "remove", "path": "/spec/flannel/podCIDRRange" }
done.

2023-02-22 09:42 UTC, ricardomaraschini commented on pkg/lint/rego/output.rego
> +			{ "op": "remove", "path": "/spec/flannel/podCIDR" }
done.

2023-02-22 09:42 UTC, ricardomaraschini commented on pkg/lint/rego/output.rego
> +			{ "op": "remove", "path": "/spec/antrea/podCidrRange" }
done.

2023-02-22 09:42 UTC, ricardomaraschini commented on pkg/lint/rego/output.rego
> +			{ "op": "remove", "path": "/spec/antrea/podCIDR" }
done.

2023-02-22 10:04 UTC, ricardomaraschini commented on pkg/lint/rego/output.rego
> +			{ "op": "replace", "path": sprintf("/spec/%v/version", [name]), "value": newest_add_on_version(name) }
I am also not sure as there are a few properties in the Installer `spec` that do not exist when we fetch the add-on versions. Things like `firewalldConfig`, `SelinuxConfig`, etc. What do you think ?  We gonna have to keep a list of all valid properties (that are not add-ons) in sync with the struct.

2023-02-22 11:12 UTC, ricardomaraschini commented on pkg/lint/rego/output.rego
> +			{ "op": "replace", "path": "/spec/openebs/version", "value": newest_add_on_version("openebs") }
Removed.

2023-02-22 11:16 UTC, ricardomaraschini commented on pkg/lint/rego/output.rego
> +			{ "op": "replace", "path": "/spec/rook/version", "value": newest_add_on_version("rook") }
Removed.

2023-02-22 11:21 UTC, ricardomaraschini commented on pkg/lint/rego/output.rego
> +			{ "op": "replace", "path": "/spec/rook/version", "value": newest_add_on_version("rook") }
I am not sure, removed.

2023-02-22 12:45 UTC, ricardomaraschini commented on pkg/lint/rego/output.rego
> +			{ "op": "replace", "path": sprintf("/spec/%v/version", [name]), "value": newest_add_on_version(name) }
I have added a new verification to check if all properties in the Installer `spec` are valid (valid as in known to the struct). This forces an error if the spec has something that is not known.

Example, for this bogus installer:
```yaml
apiVersion: "cluster.kurl.sh/v1beta1"
kind: "Installer"
metadata:
  name: "latest"
spec:
  kubernetes:
    version: 1.26.x
  containerd:
    version: latest
  weave:
    version: latest
  doesNotExist:
    something: yes
  anotherThing:
    yetSomethingElse: no
```

This is the lint return:

```yaml
- type: unknown-property
  message: Unknown installer property anotherThing
  severity: error
  patch:
  - op: remove
    path: /spec/anotherThing
- type: unknown-property
  message: Unknown installer property doesNotExist
  severity: error
  patch:
  - op: remove
    path: /spec/doesNotExist
```

2023-02-22 12:46 UTC, ricardomaraschini commented on pkg/lint/rego/output.rego
> +			{ "op": "replace", "path": sprintf("/spec/%v/version", [name]), "value": newest_add_on_version(name) }
This is the commit that added this feature: https://github.com/replicatedhq/kurlkinds/pull/63/commits/4a93141397292e98668d211aad6b81066791c81e

Can you please let me know what you think ?

2023-02-22 17:21 UTC, emosbaugh commented on pkg/lint/rego/output.rego
> +			{ "op": "replace", "path": sprintf("/spec/%v/version", [name]), "value": newest_add_on_version(name) }
im fine with this but would another approach just to be to check if newest_add_on_version can resolve a version? if not do not recommend a patch?

2023-02-22 21:55 UTC, ricardomaraschini commented on pkg/lint/rego/output.rego
> +			{ "op": "replace", "path": sprintf("/spec/%v/version", [name]), "value": newest_add_on_version(name) }
That would essentially double all the rules if I understand how Rego behaves. One with the patch and another without it. I can dig a little deeper into that tomorrow.

2023-02-22 22:17 UTC, emosbaugh commented on pkg/lint/rego/output.rego
> +			{ "op": "replace", "path": sprintf("/spec/%v/version", [name]), "value": newest_add_on_version(name) }
I am not an expert here. I am only asking a question. If you believe that your approach is better I am ok with it.

2023-02-23 08:56 UTC, ricardomaraschini commented on pkg/lint/rego/output.rego
> +			{ "op": "replace", "path": sprintf("/spec/%v/version", [name]), "value": newest_add_on_version(name) }
@emosbaugh it turned out that we gonna have to distinguish between Spec properties that refer to add-ons (`rook`, `flannel`, etc) and Spec properties that refer to other stuff (`helm`, `firewalldConfig`, etc) anyways. For the latter there is no versions available so no `newest_add_on_version` is possible.

2023-02-23 16:57 UTC, emosbaugh approved these changes

2023-03-08 20:01 UTC, laverya commented on pkg/lint/lint_test.go
> +			Versions: []string{"6.0.0", "7.0.0", "8.0.0"},
Are we actually certain that this doesn't break things?

2023-03-08 20:13 UTC, laverya approved these changes

2023-03-08 20:13 UTC, merged